
#jedis.pool.host=192.168.242.8
jedis.pool.host=hadoop2428
jedis.pool.port=6379
jedis.pool.config.password=butyet0918

KAFKA_BOOTSTRAP_SERVERS=hadoop2429:9092,hadoop2428:9092,hadoop2427:9092

cheng_du_gps_topic=cheng_du_gps_topic
hai_kou_gps_topic=hai_kou_gps_topic

hbase_connect=hadoop2429,hadoop2428,hadoop2427
hbase_offset_store=hbase_offset_store



