# ==================== Spark 相关参数 ====================
spark.worker.timeout=500
spark.rpc.askTimeout=600s
spark.network.timeout=600s
spark.cores.max=10
spark.task.maxFailures=5
spark.speculation=true
spark.driver.allowMultipleContext=true
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.buffer.pageSize=200m
spark.streaming.checkpointdir=hdfs://hadoop2429:9000/streaming
spark.streaming.kafka.maxRatePerPartition=1000
spark.streaming.backpressure.enabled=true
spark.streaming.backpressure.initialRate=10

# ==================== 起始符 ====================
initial.character=4

# ==================== HBase 配置 ====================
hbase.zookeeper.quorum=hadoop2429:2181,hadoop2428:2181,hadoop2427:2181
hbase.master=hadoop2429:60000
hbase.zookeeper.property.clientPort=2181
hbase.rpc.timeout=600000
hbase.client.operator.timeout=600000
hbase.client.scanner.timeout.period=600000

# ==================== Kafka 配置 ====================
auto.offset.reset=latest

# ==================== Redis 配置 ====================
jedis.pool.host=hadoop2428
jedis.pool.port=6379
jedis.pool.config.password=butyet0918

#匹配同步表
syn.table.order_info=order_info
syn.table.renter_info=renter_info
syn.table.driver_info=driver_info
syn.table.opt_alliance_business=opt_alliance_business
syn.table.reservation=realTime#预约单
syn.table._driver_push_tb=_driver_push_tb#司机推送表
syn.table._driver_reservation=_driver_reservation#司机预约单相关表
syn.table._join_push_reservation=_crontab_reservation#关联出的5分钟订单表
syn.table.columnFamily=MM

#sparkSQL查询表schema
order.sparksql_table_schema=id String, create_time String ,pay_all String ,open_lng String , open_lat String , begin_address_code String , charge_mileage String , city_name String , vehicle_license String , driver_id String ,driver_name String, cancel String , close_gps_time String
registe.sparksql_table_schema=id String, create_time String , last_login_city String , last_logon_time String , city_name String
hotArea.sparksql_table_schema=create_time String, open_lat String , open_lng String , begin_address_code String
drivers.spark_sql_table_schema=id String , create_time String , register_city String , driver_name String , mobile String ,driver_type String ,cancel_count String ,driver_management_id String
#司管表
opt_alliance_business.spark_sql_table_schema=(id_ String , alliance_name String , organization_code String , alliance_role String , linkman String ,contact_number String ,create_user String , create_time String , update_user String ,update_time String , state String , del_state String
#预约单的增量表
reservation.spark_sql_table_schema=(id String , driver_name String , mobile String , alliance_name String , register_city String , driver_type String , close_gps_time String , pushOrderTime String ,pushOrderNum String ,effectiveSlogan String ,grab_sus_order String , cancel_order_num String ,cancel_passenger_num String , cancel_driver_num String , cancel_service_num String ,destination_reached_num String ,pay_num String , order_cumulative_num String ,order_pay_cumulative_num String
#司机推动订单表
_driver_push_tb.spark_sql_table_schema=driver_id String , driver_name String , mobile String , alliance_name String , register_city String , driver_type String , pushOrderTime String , pushOrderNum String
#司机预约单关联表
_driver_reservation.spark_sql_table_schema=driver_id String , driver_name String , mobile String , register_city String , driver_type String , alliance_name String , effectiveSlogan String , grab_sus_order String , cancel_order_num String , cancel_passenger_num String , cancel_driver_num String , cancel_service_num String , destination_reached_num String , pay_num String , order_cumulative_num String , order_pay_cumulative_num String , pay_time String , close_gps_time String , cancel_time String , grab_sus_time String
#5分钟的增量表
_join_push_reservation.spark_sql_table_schema=driver_id String , driver_name String , mobile String , register_city String , driver_type String , alliance_name String ,driver_management_id String, pushOrderTime String , pushOrderNum String , effectiveSlogan String , grab_sus_order String , cancel_order_num String , cancel_passenger_num String , cancel_driver_num String , cancel_service_num String , destination_reached_num String , pay_num String , order_cumulative_num String , order_pay_cumulative_num String , pay_time String , close_gps_time String , cancel_time String , grab_sus_time String
#order_reservaton
order_reservaton.spark_sql_table_schema=driver_id String , create_time String ,order_type String , cancel String , state String ,pay_normal String ,pay_all String , work_flow String , close_gps_time String , pay_time String ,cancel_time String
#预约单的表
crontab_reservation.spark_sql_table_schema=driver_id String, driver_name String,mobile String, alliance_name String, driver_management_id String, register_city String , driver_type String, close_gps_time String , pushOrderTime String , pushOrderNum String , effectiveSlogan String , _effective_glab_time String, grab_sus_order String, cancel_order_num String, cancel_passenger_num String, cancel_driver_num String , cancel_service_num String, destination_reached_num String, pay_num String, order_cumulative_num String, order_pay_cumulative_num String, pay_time String , cancel_time String, grab_sus_time String

#hbase查询表schema
order.hbase_table_schema=MM:id , MM:create_time ,MM:pay_all, MM:open_lng , MM:open_lat , MM:begin_address_code , MM:charge_mileage , MM:city_name  , MM:vehicle_license , MM:driver_id ,MM:driver_name, MM:cancel , MM:close_gps_time
registe.hbase_table_schema=MM:id , MM:create_time , MM:last_login_city , MM:last_logon_time , MM:city_name
hotArea.hbase_table_schema=MM:create_time , MM:open_lat , MM:open_lng , MM:begin_address_code
driver.hbase_table_schema=MM:id, MM:create_time , MM:register_city , MM:driver_name , MM:mobile ,MM:driver_type ,MM:cancel_count ,MM:driver_management_id
#司管表
opt_alliance_business.hbase_table_schema=MM:id_ , MM:alliance_name , MM:organization_code , MM:alliance_role , MM:linkman ,MM:contact_number ,MM:create_user , MM:create_time , MM:update_user ,MM:update_time , MM:state , MM:del_state
#预约单的增量表
reservation.hbase_table_schema=MM:id , MM:driver_name , MM:mobile , MM:alliance_name , MM:register_city , MM:driver_type , MM:close_gps_time , MM:pushOrderTime , MM:pushOrderNum , MM:effectiveSlogan ,MM:grab_sus_order , MM:cancel_order_num ,MM:cancel_passenger_num , MM:cancel_driver_num , MM:cancel_service_num ,MM:destination_reached_num ,MM:pay_num , MM:order_cumulative_num ,MM:order_pay_cumulative_num
#司机推动订单表
_driver_push_tb.hbase_table_schema=MM:driver_id , MM:driver_name , MM:mobile , MM:alliance_name , MM:register_city , MM:driver_type , MM:pushOrderTime , MM:pushOrderNum
#司机预约单关联表
_driver_reservation.hbase_table_schema=MM:driver_id , MM:driver_name , MM:mobile , MM:register_city , MM:driver_type , MM:alliance_name , MM:effectiveSlogan , MM:grab_sus_order , MM:cancel_order_num , MM:cancel_passenger_num , MM:cancel_driver_num , MM:cancel_service_num , MM:destination_reached_num , MM:pay_num , MM:order_cumulative_num , MM:order_pay_cumulative_num , MM:pay_time , MM:close_gps_time , MM:cancel_time , MM:grab_sus_time
#5分钟的增量表
_join_push_reservation.hbase_table_schema=MM:driver_id , MM:driver_name , MM:mobile , MM:register_city , MM:driver_type , MM:alliance_name , MM:driver_management_id ,MM:pushOrderTime , MM:pushOrderNum ,MM:effectiveSlogan , MM:grab_sus_order , MM:cancel_order_num , MM:cancel_passenger_num , MM:cancel_driver_num , MM:cancel_service_num , MM:destination_reached_num , MM:pay_num , MM:order_cumulative_num , MM:order_pay_cumulative_num , MM:pay_time , MM:close_gps_time , MM:cancel_time , MM:grab_sus_time
#order_reservaton
order_reservaton.hbase_table_schema=MM:driver_id , MM:create_time ,MM:order_type , MM:cancel , MM:state ,MM:pay_normal ,MM:pay_all , MM:work_flow , MM:close_gps_time , MM:pay_time ,MM:cancel_time
#预约单的表
crontab_reservation.hbase_table_schema=MM:driver_id , MM:driver_name ,MM:mobile, MM:alliance_name , MM:driver_management_id , MM:register_city ,MM:driver_type , MM:close_gps_time  , MM:pushOrderTime , MM:pushOrderNum ,MM:effectiveSlogan,MM:_effective_glab_time , MM:grab_sus_order , MM:cancel_order_num , MM:cancel_passenger_num , MM:cancel_driver_num,MM:cancel_service_num , MM:destination_reached_num , MM:pay_num , MM:order_cumulative_num , MM:order_pay_cumulative_num , MM:pay_time  , MM:cancel_time , MM:grab_sus_time

#自定义数据源的别名
sparksql_table_schema=sparksql_table_schema
hbase_table_name=hbase_table_name
hbase_table_schema=hbase_table_schema

# ==================== HDFS 配置 ====================
hdfs.host=hdfs://hadoop2429:9000/hfile/