#jedisCluster????
#redisCluster????
servers=hadoop2428:6379
#??redisCluster??????
connectionTimeout=300000
#??redisCluster??????
soTimeout=300000
#??redisCluster??????
maxAttempts=6
#jedis?????
#????????
maxTotal=200
#?????????????(??)
maxWaitMillis=15000
#???????
maxIdle=50
#???????
minIdle=10
#????connection??validateObject??
testOnBorrow=true
#?????????????
blockWhenExhausted=true
#????????
lifo=true
#???????????
testOnReturn=false
#??????????
testWhileIdle=true
#???????????????testWhileIdle=true???
timeBetweenEvictionRunsMillis=30000
#????-???
cluster.key.monitor.dataProcess=MONITOR_DP
#???????-???
cluster.exptime.monitor=86400




